server:
  port: 12000
spring:
  application:
    name: teambition-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/smallbell/teambition.git
  rabbitmq:
    host: 127.0.0.1
    password: guest
    username: guest
management:       #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh